modLoader="javafml"
loaderVersion="[24,)"
issueTrackerURL="https://github.com/ThexXTURBOXx/Reforged/issues"
displayURL="http://minecraft.curseforge.com/projects/reforged"
logoFile="logo.png"
credits="Snow_Yoshi98, baddaspig and Sunconure11 for textures. DenTheUA for translation."
authors="ThexXTURBOXx, Silvercatcher"
[[mods]]
    modId="reforged"
    version="${file.jarVersion}"
    displayName="Reforged"
    updateJSONURL="https://raw.githubusercontent.com/ThexXTURBOXx/UpdateJSONs/master/reforged.json"
    description='''
A successor (not port) of Balkon's Weapon Mod.

The mod adds primitive, medieval and some gunpowder weapons.
'''